Name=input("enter the name")
print("my name is",Name)
Age=int(input("enter the age"))
print("my age is",Age)
School=input("enter the school")
print("I was studied in",School)
Group=input("enter the group")
print("my group is",Group)
Place=input("enter the place")
print("i live in",Place)
DOB=input("enter the DOB")
print("I was born in",DOB)
Hobby=input("enter the hobby")
print("My hobby is",Hobby)