Name=input("enter the name")
Age=int(input("enter the age"))
Seat_Type=input("enter the seat type seated or beded")
Bus_Type=input("enter AC or non AC")
Travels_Name=input("enter the travels name")
Destination_From=input("enter the location you where")
Destination_To=input("enter the destination To")
Departure_Time=input("enter the time of departure")
Arrival_Time=input("enter the time of arrival")
print("Name:",Name)
print("Age:",Age)
print("Seat Type:",Seat_Type)
print("Bus Type;",Bus_Type)
print("Travels Name:",Travels_Name)
print("Destination From:",Destination_From)
print("Destination To:",Destination_To)
print("Departure Time:",Departure_Time)
print("Arrival Time:",Arrival_Time)

print("haii")